name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      # Gradle setup incl. caching
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Spotless check
        run: ./gradlew spotlessCheck --stacktrace --warning-mode=all

      - name: Build & test
        run: ./gradlew build --info --stacktrace --warning-mode=all

      # Always upload test reports when something fails
      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/test-results/test/*.xml
            **/build/reports/tests/test/**
            **/build/reports/spotbugs/**

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4